routes/admin.php
<?php

use App\Http\Controllers\Admin\{
    AdminController,
    CrudController,
    DashboardController,
    PermissionController,
    ProfileController,
    RoleController
};

use Illuminate\Support\Facades\Route;


Route::prefix('admin')->as('admin.')->middleware(['auth:admin'])->group(function () {

    # Admin
    Route::controller(AdminController::class)->group(function() {
        Route::get('/', 'index')->name("index");
        Route::get('/create', 'create')->name("create");
        Route::post('/store', 'store')->name("store");
        Route::post('/edit', 'edit')->name("edit");
        Route::get('/delete', 'delete')->name("delete");

    });

    # Dashboard
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::controller(CrudController::class)->name('crud.')->prefix('crud')->group(function () {

        Route::get('get-all-data', 'getAllData')->name('get-all-data');
        Route::get('/', 'index')->name('index');
        Route::post('store', 'store')->name('store');
        Route::delete('{crud}', 'destroy')->name('destroy');
        Route::get('{crud}', 'show')->name('view');

        Route::post('{crud}', 'update')->name('update');
    });

    Route::controller(ProfileController::class)->name('profile')->prefix('profile')->group(function() {
        Route::get('/', 'index');
        Route::post('/update', 'update')->name('.update');
        Route::post('/update/password', 'updatePassword')->name('.update_password');
        Route::post('/update/profile', 'updateProfile')->name('.update_profile');
    });

    # Permission
    Route::middleware("authorized")->controller(PermissionController::class)->name('permission.')->prefix('permission')->group(function() {
        Route::get('/', 'index');
        Route::post('/store', 'store')->name('store');
        Route::post('/update/{permission}', 'update')->name('update');
        Route::delete('/delete/{permission}', 'delete')->name('delete');
    });

    # Role
    Route::middleware("authorized")->controller(RoleController::class)->name('role.')->prefix('role')->group(function() {
        Route::get('/', 'index');
        Route::get('/create', 'create')->name('create');
        Route::get('/edit/{role}', 'edit')->name('edit');
        Route::post('/store', 'store')->name('store');
        Route::post('/update/{role}', 'update')->name('update');
        Route::delete('/delete/{role}', 'delete')->name('delete');
    });

});

routes/web.php
<?php

use App\Models\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CRUDController;
use App\Models\Foo;

Route::get('/', function () {

    // return view('layouts.frontend_app');
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');



Route::get('/test', function () {
    $admins = Admin::all();
    return view('backend.crud.test',compact('admins'));
});




# SummerNote Image Upload
Route::post('upload', function (Request $request) {
    $image = $request->file('file');
    $filename = uniqid() . '.' . $image->getClientOriginalExtension();
    $path = $image->storeAs('public/images', $filename);

    return response()->json([
        'url' => asset('storage/images/' . $filename),
    ]);
});


Route::get('query',[CRUDController::class,'index']);

Route::post("media-upload",function(Request $request) {
    Foo::create([
        "name" => $request->name,
        "image" => $request->image,
    ]);

    return back();
})->name("media_upload");


Route::post("csv-upload",function(Request $request) {

    if ($request->has('csv')) {
        $csv = file($request->file('csv'));
        $chunks = array_chunk($csv, 1000);
        $path = resource_path('temp');
        foreach ($chunks as $key => $chunk) {
            $name = "/tmp{$key}.csv";
            file_put_contents($path . $name, $chunk);
        }

        $files = glob("$path/*.csv");
        $header = [];
        foreach ($files as $key => $file) {
            $data = array_map('str_getcsv', file($file));
            if ($key == 0) {
                $header = $data[0];
                unset($data[0]);
            }

            foreach ($data as $user) {
                $userData = array_combine($header, $user);

                Foo::create([
                    "name" => $userData["Name"],
                    "image" => $userData["Image"],
                ]);
            }

            unlink($file);
        }
        return "stored";
    }
    return $request;
})->name("csv_upload");



// public function importUsingChunk(Request $request)
// {
//     if ($request->has('csv')) {
//         $csv = file($request->file('csv'));
//         $chunks = array_chunk($csv, 1000);
//         $path = resource_path('temp');
//         foreach ($chunks as $key => $chunk) {
//             $name = "/tmp{$key}.csv";
//             file_put_contents($path . $name, $chunk);
//         }

//         $files = glob("$path/*.csv");
//         $header = [];
//         foreach ($files as $key => $file) {
//             $data = array_map('str_getcsv', file($file));
//             if ($key == 0) {
//                 $header = $data[0];
//                 unset($data[0]);
//             }

//             foreach ($data as $user) {
//                 $userData = array_combine($header, $user);

//                 User::create([
//                     "name" => $userData["Name"],
//                     "email" => $userData["Email"],
//                     "password" => $userData["Password"],
//                     "city" => $userData["City"],
//                 ]);
//             }

//             unlink($file);
//         }
//         return "stored";
//     }
//     return "please upload csv file";
// }

resources/views/backend/admin/create.blade.php
@extends('layouts.backend_master')
@section('title', 'Admin Create')
@push('css')

@endpush
@section('master_content')
<div class="container">
    <form action="{{ route('admin.store') }}" method="POST">
        @csrf
        <div class="row">
            <div class="col-md-3 my-2">
                <input type="text" class="form-control" name="name">
            </div>
            <div class="col-md-3 my-2">
                <input type="email" class="form-control" name="email">
            </div>
            <div class="col-md-3 my-2">
                <input type="password" class="form-control" name="password">
            </div>
            <div class="col-md-3 my-2">
                <select name="role" id="" class="form-control">
                    <option value="">Select Role</option>
                    @foreach ($roles as $role)
                    <option value="{{ $role->id }}">{{ $role->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-md-3 my-2">
                <button class="btn btn-sm btn-success">Submit</button>
            </div>
        </div>
    </form>
</div>

@endsection

@push('script')


<script>

</script>
@endpush

resources/views/backend/admin/index.blade.php
@extends('layouts.backend_master')
@section('title', 'Admin')
@push('css')
<x-utility.datatable-css/>
@endpush
@section('master_content')
<div class="container">
    <table class="table table-sm table-bordered data-table text-centerd" id="table_id">
        <thead>
            <tr>
                <th width="2%"><input type="checkbox"></th>
                <th>SL</th>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Action</th>
            </tr>
        </thead>

        <tbody class="text-center">

        </tbody>
    </table>
</div>

@endsection

@push('script')
<x-utility.datatable-js/>
<script>
      $(function () {
    var table = $('.data-table').DataTable({
        "processing": true,
        "retrieve": true,
        "serverSide": true,
        'paginate': true,
        'searchDelay': 700,
        "bDeferRender": true,
        "responsive": true,
        "autoWidth": true,
        "order": [ [0, 'desc'] ],
        ajax: "{{ route('admin.index') }}",
        columns: [
            {data: '#',orderable: false,},
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'roles[0].name', name: 'roles'},
            {data: 'actions', name: 'actions',orderable: false,},
        ],
    });
  });
</script>

@endpush