routes/admin.php
<?php

use App\Http\Controllers\Admin\{
    AdminController,
    CrudController,
    DashboardController,
    PermissionController,
    ProfileController,
    RoleController
};

use Illuminate\Support\Facades\Route;


Route::prefix('admin')->as('admin.')->middleware(['auth:admin'])->group(function () {

    # Admin
    Route::controller(AdminController::class)->group(function() {
        Route::get('/', 'index')->name("index");
        Route::get('/create', 'create')->name("create");
        Route::post('/store', 'store')->name("store");
        Route::post('/edit', 'edit')->name("edit");
        Route::get('/delete', 'delete')->name("delete");

    });

    # Dashboard
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::controller(CrudController::class)->name('crud.')->prefix('crud')->group(function () {

        Route::get('get-all-data', 'getAllData')->name('get-all-data');
        Route::get('/', 'index')->name('index');
        Route::post('store', 'store')->name('store');
        Route::delete('{crud}', 'destroy')->name('destroy');
        Route::get('{crud}', 'show')->name('view');

        Route::post('{crud}', 'update')->name('update');
    });

    Route::controller(ProfileController::class)->name('profile')->prefix('profile')->group(function() {
        Route::get('/', 'index');
        Route::post('/update', 'update')->name('.update');
        Route::post('/update/password', 'updatePassword')->name('.update_password');
        Route::post('/update/profile', 'updateProfile')->name('.update_profile');
    });

    # Permission
    Route::middleware("authorized")->controller(PermissionController::class)->name('permission.')->prefix('permission')->group(function() {
        Route::get('/', 'index');
        Route::post('/store', 'store')->name('store');
        Route::post('/update/{permission}', 'update')->name('update');
        Route::delete('/delete/{permission}', 'delete')->name('delete');
    });

    # Role
    Route::middleware("authorized")->controller(RoleController::class)->name('role.')->prefix('role')->group(function() {
        Route::get('/', 'index');
        Route::get('/create', 'create')->name('create');
        Route::get('/edit/{role}', 'edit')->name('edit');
        Route::post('/store', 'store')->name('store');
        Route::post('/update/{role}', 'update')->name('update');
        Route::delete('/delete/{role}', 'delete')->name('delete');
    });

});

routes/web.php
<?php

use App\Models\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CRUDController;
use App\Models\Foo;

Route::get('/', function () {

    // return view('layouts.frontend_app');
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');



Route::get('/test', function () {
    $admins = Admin::all();
    return view('backend.crud.test',compact('admins'));
});




# SummerNote Image Upload
Route::post('upload', function (Request $request) {
    $image = $request->file('file');
    $filename = uniqid() . '.' . $image->getClientOriginalExtension();
    $path = $image->storeAs('public/images', $filename);

    return response()->json([
        'url' => asset('storage/images/' . $filename),
    ]);
});


Route::get('query',[CRUDController::class,'index']);

Route::post("media-upload",function(Request $request) {
    Foo::create([
        "name" => $request->name,
        "image" => $request->image,
    ]);

    return back();
})->name("media_upload");


Route::post("csv-upload",function(Request $request) {

    if ($request->has('csv')) {
        $csv = file($request->file('csv'));
        $chunks = array_chunk($csv, 1000);
        $path = resource_path('temp');
        foreach ($chunks as $key => $chunk) {
            $name = "/tmp{$key}.csv";
            file_put_contents($path . $name, $chunk);
        }

        $files = glob("$path/*.csv");
        $header = [];
        foreach ($files as $key => $file) {
            $data = array_map('str_getcsv', file($file));
            if ($key == 0) {
                $header = $data[0];
                unset($data[0]);
            }

            foreach ($data as $user) {
                $userData = array_combine($header, $user);

                Foo::create([
                    "name" => $userData["Name"],
                    "image" => $userData["Image"],
                ]);
            }

            unlink($file);
        }
        return "stored";
    }
    return $request;
})->name("csv_upload");



// public function importUsingChunk(Request $request)
// {
//     if ($request->has('csv')) {
//         $csv = file($request->file('csv'));
//         $chunks = array_chunk($csv, 1000);
//         $path = resource_path('temp');
//         foreach ($chunks as $key => $chunk) {
//             $name = "/tmp{$key}.csv";
//             file_put_contents($path . $name, $chunk);
//         }

//         $files = glob("$path/*.csv");
//         $header = [];
//         foreach ($files as $key => $file) {
//             $data = array_map('str_getcsv', file($file));
//             if ($key == 0) {
//                 $header = $data[0];
//                 unset($data[0]);
//             }

//             foreach ($data as $user) {
//                 $userData = array_combine($header, $user);

//                 User::create([
//                     "name" => $userData["Name"],
//                     "email" => $userData["Email"],
//                     "password" => $userData["Password"],
//                     "city" => $userData["City"],
//                 ]);
//             }

//             unlink($file);
//         }
//         return "stored";
//     }
//     return "please upload csv file";
// }

resources/views/backend/includes/breadcumb.blade.php
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Dashboard</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Dashboard v1</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>

resources/views/backend/includes/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

resources/views/backend/includes/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('Backend') }}/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>

resources/views/backend/includes/preloader.blade.php
{{-- <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{{ asset('Backend') }}/dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
  </div> --}}

resources/views/backend/includes/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ route('admin.dashboard') }}" class="brand-link">
      <img src="{{ asset('Backend') }}/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">KIT</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ asset('Backend') }}/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="{{ route('admin.dashboard') }}" class="d-block">{{ auth()->user()->name }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item @if (navMenuActive(request()->segment(2)))
            menu-open
          @endif "> <!-- menu-open : Dynamic Menu Open-->
            <a href="#" class="nav-link ">
              <i class="nav-icon fa fa-gear"></i>
              <p>
                Settings
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('admin.role.') }}" class="nav-link "> <!-- active : for active  -->
                    <i class="fa-solid fa-person-shelter nav-icon" ></i>
                  <p>Role</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('admin.permission.') }}" class="nav-link ">
                <i class="fa-solid fa-person-dots-from-line nav-icon"></i>
                  <p>Permission</p>
                </a>
              </li>

            </ul>
          </li>
          <li class="nav-item"> <!-- menu-open : Dynamic Menu Open-->
            <a href="#" class="nav-link ">
              <i class="nav-icon fa fa-users"></i>
              <p>
                Admins
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('admin.index') }}" class="nav-link ">
                    <i class="fa-solid fa-user-tie nav-icon"></i>
                  <p>Manage</p>
                </a>
              </li>

            </ul>
          </li>
          {{-- <li class="nav-item">
            <a href="@route('category.index')" class="nav-link">
              <i class="nav-icon far fa-circle text-warning"></i>
              <p>Category</p>
            </a>
          </li>

        </li>
        <li class="nav-item">
            <a href="@route('cache')" class="nav-link">
              <i class="nav-icon far fa-circle text-warning"></i>
              <p>Cache</p>
            </a>
          </li>
        <li class="nav-item">
          <a href="@route('skill.index')" class="nav-link">
            <i class="nav-icon far fa-circle text-warning"></i>
            <p>Skill</p>
          </a>
        </li> --}}
        <li class="nav-item">
            <a class="nav-link" href="{{ route('admin.crud.index') }}">
              <i class="nav-icon far fa-circle "></i>
              <p>Crud</p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('admin.profile') }}">
                <i class="fa-solid fa-id-badge nav-icon"></i>
              <p>Profile</p>
            </a>
          </li>
          @auth('admin')
          <li class="nav-item">
            <form action="{{ route('admin.logout') }}" method="POST">
                @csrf
                <button class="btn btn-success btn-block">Logout</button>
            </form>
          </li>
          @endauth
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>