routes/admin.php
<?php

use App\Http\Controllers\Admin\{
    AdminController,
    CrudController,
    DashboardController,
    PermissionController,
    ProfileController,
    RoleController
};

use Illuminate\Support\Facades\Route;


Route::prefix('admin')->as('admin.')->middleware(['auth:admin'])->group(function () {

    # Admin
    Route::controller(AdminController::class)->group(function() {
        Route::get('/', 'index')->name("index");
        Route::get('/create', 'create')->name("create");
        Route::post('/store', 'store')->name("store");
        Route::post('/edit', 'edit')->name("edit");
        Route::get('/delete', 'delete')->name("delete");

    });

    # Dashboard
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::controller(CrudController::class)->name('crud.')->prefix('crud')->group(function () {

        Route::get('get-all-data', 'getAllData')->name('get-all-data');
        Route::get('/', 'index')->name('index');
        Route::post('store', 'store')->name('store');
        Route::delete('{crud}', 'destroy')->name('destroy');
        Route::get('{crud}', 'show')->name('view');

        Route::post('{crud}', 'update')->name('update');
    });

    Route::controller(ProfileController::class)->name('profile')->prefix('profile')->group(function() {
        Route::get('/', 'index');
        Route::post('/update', 'update')->name('.update');
        Route::post('/update/password', 'updatePassword')->name('.update_password');
        Route::post('/update/profile', 'updateProfile')->name('.update_profile');
    });

    # Permission
    Route::middleware("authorized")->controller(PermissionController::class)->name('permission.')->prefix('permission')->group(function() {
        Route::get('/', 'index');
        Route::post('/store', 'store')->name('store');
        Route::post('/update/{permission}', 'update')->name('update');
        Route::delete('/delete/{permission}', 'delete')->name('delete');
    });

    # Role
    Route::middleware("authorized")->controller(RoleController::class)->name('role.')->prefix('role')->group(function() {
        Route::get('/', 'index');
        Route::get('/create', 'create')->name('create');
        Route::get('/edit/{role}', 'edit')->name('edit');
        Route::post('/store', 'store')->name('store');
        Route::post('/update/{role}', 'update')->name('update');
        Route::delete('/delete/{role}', 'delete')->name('delete');
    });

});

routes/web.php
<?php

use App\Models\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CRUDController;
use App\Models\Foo;

Route::get('/', function () {

    // return view('layouts.frontend_app');
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');



Route::get('/test', function () {
    $admins = Admin::all();
    return view('backend.crud.test',compact('admins'));
});




# SummerNote Image Upload
Route::post('upload', function (Request $request) {
    $image = $request->file('file');
    $filename = uniqid() . '.' . $image->getClientOriginalExtension();
    $path = $image->storeAs('public/images', $filename);

    return response()->json([
        'url' => asset('storage/images/' . $filename),
    ]);
});


Route::get('query',[CRUDController::class,'index']);

Route::post("media-upload",function(Request $request) {
    Foo::create([
        "name" => $request->name,
        "image" => $request->image,
    ]);

    return back();
})->name("media_upload");


Route::post("csv-upload",function(Request $request) {

    if ($request->has('csv')) {
        $csv = file($request->file('csv'));
        $chunks = array_chunk($csv, 1000);
        $path = resource_path('temp');
        foreach ($chunks as $key => $chunk) {
            $name = "/tmp{$key}.csv";
            file_put_contents($path . $name, $chunk);
        }

        $files = glob("$path/*.csv");
        $header = [];
        foreach ($files as $key => $file) {
            $data = array_map('str_getcsv', file($file));
            if ($key == 0) {
                $header = $data[0];
                unset($data[0]);
            }

            foreach ($data as $user) {
                $userData = array_combine($header, $user);

                Foo::create([
                    "name" => $userData["Name"],
                    "image" => $userData["Image"],
                ]);
            }

            unlink($file);
        }
        return "stored";
    }
    return $request;
})->name("csv_upload");



// public function importUsingChunk(Request $request)
// {
//     if ($request->has('csv')) {
//         $csv = file($request->file('csv'));
//         $chunks = array_chunk($csv, 1000);
//         $path = resource_path('temp');
//         foreach ($chunks as $key => $chunk) {
//             $name = "/tmp{$key}.csv";
//             file_put_contents($path . $name, $chunk);
//         }

//         $files = glob("$path/*.csv");
//         $header = [];
//         foreach ($files as $key => $file) {
//             $data = array_map('str_getcsv', file($file));
//             if ($key == 0) {
//                 $header = $data[0];
//                 unset($data[0]);
//             }

//             foreach ($data as $user) {
//                 $userData = array_combine($header, $user);

//                 User::create([
//                     "name" => $userData["Name"],
//                     "email" => $userData["Email"],
//                     "password" => $userData["Password"],
//                     "city" => $userData["City"],
//                 ]);
//             }

//             unlink($file);
//         }
//         return "stored";
//     }
//     return "please upload csv file";
// }

app/Models/Permission.php
<?php

namespace App\Models;

use Laratrust\Models\Permission as PermissionModel;

class Permission extends PermissionModel
{
    public $guarded = [];

    public $timestamps = false;

    public function getPermission()
    {
        return $this::orderBy('description')->get();
    }

    public function savePermission($request) : self
    {
        $this->name = $request->name;
        $this->display_name = $request->display_name;
        $this->description = $request->description;
        $this->save();

        return $this;
    }

    public function updatePermission($permission, $request)
    {
        $permission->update([
           'name' => $request->name,
           'display_name' => $request->display_name,
           'description' => $request->description
        ]);

        return $this;
    }


}

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Permission;
use Illuminate\Http\Request;

class PermissionController extends Controller
{

    public function index(Request $request)
    {
        $permissions = Permission::all();

        return view('backend.settings.permission.index',compact('permissions'));
    }

    public function store(Permission $permission, Request $request)
    {
        $request->validate([
            'name' => 'required|unique:permissions',
            'display_name' => 'required|unique:permissions',
            'description' => 'required'
        ]);
        $permission->savePermission($request);
        session()->flash('success',"Permission Created!");
        return redirect()->route('admin.permission.');
    }

    public function edit(Permission $permission)
    {
        return view('admin.settings.permission.modal._edit',compact('permission'))->render();
    }

    public function update(Permission $permission, Request $request)
    {
        $permission->updatePermission($permission, $request);

        $this->success('success','Permission updated successfully!');

        return back();
    }

    public function delete(Permission $permission)
    {
        $permission->delete();

        return back();
    }
}

resources/views/backend/settings/permission/modal/_create.blade.php
<!-- Add Modal -->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form action="{{ route('admin.permission.store') }}" method="POST" class="needs-validation">
                @csrf
            <div class="row">
                <div class="col mb-3">
                  <label for="name" class="form-label">Name</label> <span class="text-danger"> *</span>
                  <input type="text" name="name" id="name" class="form-control" placeholder="DashboardController@index" required value="{{ old('name') }}">
                  <div class="invalid-tooltip">Please choose a unique and valid permission name.</div>
                </div>
              </div>
              <div class="row g-2">
                <div class="col mb-0">
                  <label for="display_name" class="form-label">Display Name</label><span class="text-danger"> *</span>
                  <input type="text" name="display_name" id="display_name" class="form-control" placeholder="View Dashboard" required value="{{ old('display_name') }}">
                  <div class="invalid-tooltip">Please choose a unique and valid display name.</div>
                </div>
                <div class="col mb-0">
                  <label for="description" class="form-label">Description</label><span class="text-danger"> *</span>
                  <input type="text" name="description" id="description" class="form-control" placeholder="Dashboard" required value="{{ old('description') }}">
                  <div class="invalid-tooltip">Please choose a description for this permission.</div>
                </div>
              </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">
                Close
              </button>
              <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </form>
      </div>
    </div>
  </div>

resources/views/backend/settings/permission/modal/_edit.blade.php
@foreach ($permissions as $permission)
<!-- Add Modal -->
<div class="modal fade" id="editModal_{{ $permission->id }}" tabindex="-1" role="dialog" aria-labelledby="addModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="addModalLabel">Edit Permission</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form action="{{ route('admin.permission.update',$permission->id) }}" method="POST" class="needs-validation">
                @csrf
            <div class="row">
                <div class="col mb-3">
                  <label for="name" class="form-label">Name</label> <span class="text-danger"> *</span>
                  <input type="text" name="name" id="name" class="form-control" placeholder="DashboardController@index" required value="{{ $permission->name }}">
                  <div class="invalid-tooltip">Please choose a unique and valid permission name.</div>
                </div>
              </div>
              <div class="row g-2">
                <div class="col mb-0">
                  <label for="display_name" class="form-label">Display Name</label><span class="text-danger"> *</span>
                  <input type="text" name="display_name" id="display_name" class="form-control" placeholder="View Dashboard" required value="{{ $permission->display_name }}">
                  <div class="invalid-tooltip">Please choose a unique and valid display name.</div>
                </div>
                <div class="col mb-0">
                  <label for="description" class="form-label">Description</label><span class="text-danger"> *</span>
                  <input type="text" name="description" id="description" class="form-control" placeholder="Dashboard" required value="{{ $permission->description }}">
                  <div class="invalid-tooltip">Please choose a description for this permission.</div>
                </div>
              </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">
                Close
              </button>
              <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </form>
      </div>
    </div>
  </div>

@endforeach