routes/admin.php
<?php

use App\Http\Controllers\Admin\{
    AdminController,
    CrudController,
    DashboardController,
    PermissionController,
    ProfileController,
    RoleController
};

use Illuminate\Support\Facades\Route;


Route::prefix('admin')->as('admin.')->middleware(['auth:admin'])->group(function () {

    # Admin
    Route::controller(AdminController::class)->group(function() {
        Route::get('/', 'index')->name("index");
        Route::get('/create', 'create')->name("create");
        Route::post('/store', 'store')->name("store");
        Route::post('/edit', 'edit')->name("edit");
        Route::get('/delete', 'delete')->name("delete");

    });

    # Dashboard
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::controller(CrudController::class)->name('crud.')->prefix('crud')->group(function () {

        Route::get('get-all-data', 'getAllData')->name('get-all-data');
        Route::get('/', 'index')->name('index');
        Route::post('store', 'store')->name('store');
        Route::delete('{crud}', 'destroy')->name('destroy');
        Route::get('{crud}', 'show')->name('view');

        Route::post('{crud}', 'update')->name('update');
    });

    Route::controller(ProfileController::class)->name('profile')->prefix('profile')->group(function() {
        Route::get('/', 'index');
        Route::post('/update', 'update')->name('.update');
        Route::post('/update/password', 'updatePassword')->name('.update_password');
        Route::post('/update/profile', 'updateProfile')->name('.update_profile');
    });

    # Permission
    Route::middleware("authorized")->controller(PermissionController::class)->name('permission.')->prefix('permission')->group(function() {
        Route::get('/', 'index');
        Route::post('/store', 'store')->name('store');
        Route::post('/update/{permission}', 'update')->name('update');
        Route::delete('/delete/{permission}', 'delete')->name('delete');
    });

    # Role
    Route::middleware("authorized")->controller(RoleController::class)->name('role.')->prefix('role')->group(function() {
        Route::get('/', 'index');
        Route::get('/create', 'create')->name('create');
        Route::get('/edit/{role}', 'edit')->name('edit');
        Route::post('/store', 'store')->name('store');
        Route::post('/update/{role}', 'update')->name('update');
        Route::delete('/delete/{role}', 'delete')->name('delete');
    });

});

routes/web.php
<?php

use App\Models\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CRUDController;
use App\Models\Foo;

Route::get('/', function () {

    // return view('layouts.frontend_app');
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');



Route::get('/test', function () {
    $admins = Admin::all();
    return view('backend.crud.test',compact('admins'));
});




# SummerNote Image Upload
Route::post('upload', function (Request $request) {
    $image = $request->file('file');
    $filename = uniqid() . '.' . $image->getClientOriginalExtension();
    $path = $image->storeAs('public/images', $filename);

    return response()->json([
        'url' => asset('storage/images/' . $filename),
    ]);
});


Route::get('query',[CRUDController::class,'index']);

Route::post("media-upload",function(Request $request) {
    Foo::create([
        "name" => $request->name,
        "image" => $request->image,
    ]);

    return back();
})->name("media_upload");


Route::post("csv-upload",function(Request $request) {

    if ($request->has('csv')) {
        $csv = file($request->file('csv'));
        $chunks = array_chunk($csv, 1000);
        $path = resource_path('temp');
        foreach ($chunks as $key => $chunk) {
            $name = "/tmp{$key}.csv";
            file_put_contents($path . $name, $chunk);
        }

        $files = glob("$path/*.csv");
        $header = [];
        foreach ($files as $key => $file) {
            $data = array_map('str_getcsv', file($file));
            if ($key == 0) {
                $header = $data[0];
                unset($data[0]);
            }

            foreach ($data as $user) {
                $userData = array_combine($header, $user);

                Foo::create([
                    "name" => $userData["Name"],
                    "image" => $userData["Image"],
                ]);
            }

            unlink($file);
        }
        return "stored";
    }
    return $request;
})->name("csv_upload");



// public function importUsingChunk(Request $request)
// {
//     if ($request->has('csv')) {
//         $csv = file($request->file('csv'));
//         $chunks = array_chunk($csv, 1000);
//         $path = resource_path('temp');
//         foreach ($chunks as $key => $chunk) {
//             $name = "/tmp{$key}.csv";
//             file_put_contents($path . $name, $chunk);
//         }

//         $files = glob("$path/*.csv");
//         $header = [];
//         foreach ($files as $key => $file) {
//             $data = array_map('str_getcsv', file($file));
//             if ($key == 0) {
//                 $header = $data[0];
//                 unset($data[0]);
//             }

//             foreach ($data as $user) {
//                 $userData = array_combine($header, $user);

//                 User::create([
//                     "name" => $userData["Name"],
//                     "email" => $userData["Email"],
//                     "password" => $userData["Password"],
//                     "city" => $userData["City"],
//                 ]);
//             }

//             unlink($file);
//         }
//         return "stored";
//     }
//     return "please upload csv file";
// }

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\{
    DB,Log
};

use Laratrust\Models\Role as RoleModel;
use Illuminate\Database\Eloquent\Relations\{BelongsToMany};

class Role extends RoleModel
{
    public $guarded = [];

    public $timestamps = false;



    public function users() : BelongsToMany
    {
        return $this->belongsToMany(User::class,'role_user');
    }

    public function getRole()
    {
        return $this::orderBy('name','asc')->get();
    }

    public function saveRole($request) : Role
    {
        DB::beginTransaction();
        try {
            $this->name = $request->name;
            $this->display_name = $request->display_name;
            $this->description = $request->description;
            $this->save();

            if($request->has('permissions')) {
                $this->permissions()->sync($request->permissions);
            }
        } catch (\Exception $e) {
            DB::rollback();
            Log::error('Role Create failed :: ' . $e->getMessage());
        }
        DB::commit();

        return $this;
    }

    public function updateRole($role, $request) : Role
    {
        DB::beginTransaction();
        try {
            $role->name = $request->name;
            $role->display_name = $request->display_name;
            $role->description = $request->description;
            $role->save();

            if($request->has('permissions')) {
                $role->permissions()->sync($request->permissions);
            }
        } catch (\Exception $e) {
            DB::rollback();
            Log::error('Role Update failed :: ' . $e->getMessage());
        }
        DB::commit();

        return $this;
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Role;
use App\Models\Permission;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RoleController extends Controller
{
    public function index(Role $role, Request $request)
    {

        // if ($request->ajax()) {
        //      $data = $role->getRole();

        //     return DataTables::of($data)
        //         ->addIndexColumn()
        //         ->addColumn('action', function($row){
        //             $editLink = route('role.edit',$row->id);
        //             $deleteLink = route('role.delete',$row->id);
        //             return getDynamicPointButtonLink($editLink, $deleteLink);
        //         })
        //         ->rawColumns(['action'])
        //         ->make(true);
        // }
        $roles = $role->getRole();
        return view('backend.settings.role.index',compact("roles"));
    }

    public function create(Permission $permission)
    {
        $permissions = $permission->getPermission();

        return view('backend.settings.role.create',[
            'permissions' => $permissions
        ]);
    }

    public function store(Role $role, Request $request)
    {
        $request->validate([
            'name' => 'required|unique:roles',
            'display_name' => 'required|unique:roles'
        ]);
        $role->saveRole($request);

        return redirect()->route('admin.role.');
    }

    public function edit(Role $role, Permission $permission)
    {
      $permissions  = $permission->getPermission();

       $userRolePermissions = userRolePermissions($role->id);

      $role_permission       = [];

      foreach($userRolePermissions as $r) {
         $role_permission[$r->permission_id] = 1;
      }

      return view('backend.settings.role.edit',[
        'permissions' => $permissions,
        'role' => $role,
        'role_permission' => $role_permission
      ]);
    }

    public function update(Role $role, Request $request)
    {
        $request->validate([
            'name' => 'required',
            'display_name' => 'required'
        ]);

      
        $role->updateRole($role, $request);

        return redirect()->route('admin.role.');
    }

    public function delete(Role $role)
    {
        $role->delete();

        return redirect()->route('admin.role.');
    }
}

resources/views/backend/settings/role/create.blade.php
@extends('layouts.backend_master')
@section('title', 'Role')
@push('css')
{{-- <x-utility.data-table-css/> --}}
@endpush
@section('master_content')
<div class="card">
    <div class="card-header ">
        <div class="d-flex justify-content-between">
        <h4 class="card-title">Create Role </h4>
        <a href="{{ route('admin.role.') }}" class="btn btn-success btn-sm"><i class="fa fa-angle-back"></i> Back</a>
        </div>

    </div>
    <div class="card-body">
        <div class="card">
            <div class="card-body">
             <form
                action="{{ route('admin.role.store') }}"
                method="post"
                class="needs--validation"
                role="form"
                novalidate
            >
            @csrf
            <div class="row">
                <div class="col mb-3">
                <label for="nameBasic" class="form-label">Name</label>
                <input type="text" name="name" id="nameBasic" class="form-control" placeholder="Enter Name" required>
                <div class="invalid-tooltip">Please choose a unique and valid role name.</div>
                </div>
            </div>
            <div class="row g-2">
                <div class="col mb-0">
                <label for="emailBasic" class="form-label">Display Name</label>
                <input type="text" name="display_name" id="emailBasic" class="form-control" placeholder="Display Name" required>
                <div class="invalid-tooltip">Please choose a unique and valid display name.</div>
                </div>
                <div class="col mb-0">
                <label for="dobBasic" class="form-label">Description</label>
                <input type="text" name="description" id="dobBasic" class="form-control" placeholder="Description" required>
                <div class="invalid-tooltip">Please choose a description for this role.</div>
                </div>
            </div>

            <hr>

            @php  $previous_permission = "";  @endphp

            <div class="">
                <input
                    type="checkbox"
                    id="selectAll"
                    class="form-check-input"
                />
                <label class="checkboxSuccess1" for="selectAll" id="replace">Select All</label>
            </div>
                <div class="form--inline">
                    @foreach ($permissions as $permission)
                        @if($previous_permission != $permission->description)
                            <div class="col mb-0" style="margin-top:10px;">
                                <input
                                    type="checkbox"
                                    class="form-check-input {{ lcfirst($permission->description) }}"
                                    value="{{$permission->id}}"
                                    onClick="selectPermission('{{ lcfirst($permission->description) }}')"
                                />
                                <label class="form-label">{{ ucfirst($permission->description) }}</label>
                            </div>
                        @endif
                            <div class="form-check form-switch mb-2 form-inline">
                                <input
                                    class="form-check-input"
                                    id="{{ lcfirst($permission->description) }}"
                                    type="checkbox"
                                    id="{{$permission->id}}"
                                    name="permissions[]"
                                    value="{{$permission->id}}"
                                    @php if(isset($role_permission[$permission->id]) && $role_permission[$permission->id]) { @endphp checked @php }
                                    @endphp
                                >
                                <label class="form-check-label" for="{{$permission->id}}">{{$permission->display_name}}</label>
                            </div>
                            @php
                                $previous_permission = $permission->description;
                                $check = isset( $permissions[$loop->index +1]->description) ? $permissions[$loop->index +1]->description : "-";
                            @endphp
                            @if($previous_permission != $check || $check == '-')@endif
                        @endforeach
                    </div>
                    <div class="fw-bold py-1 mt-3">
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
            </form>
        </div>
    </div>
    </div>
</div>


@endsection

@push('script')
{{-- <x-utility.data-table-js/> --}}
<script>


</script>
@endpush

resources/views/backend/settings/role/edit.blade.php
@extends('layouts.backend_master')
@section('title', 'Role')
@push('css')
{{-- <x-utility.data-table-css/> --}}
@endpush
@section('master_content')
<div class="card">
    <div class="card-header ">
        <div class="d-flex justify-content-between">
        <h4 class="card-title">Update Role </h4>
        <a href="{{ route('admin.role.') }}" class="btn btn-success btn-sm"><i class="fa fa-angle-back"></i> Back</a>
        </div>

    </div>
    <div class="card-body">
        <div class="card">
            <div class="card-body">
             <form
                action="{{ route('admin.role.update',$role->id) }}"
                method="post"
                class="needs--validation"
                role="form"
                novalidate
            >
            @csrf
            <div class="row">
                <div class="col mb-3">
                <label for="nameBasic" class="form-label">Name</label>
                <input type="text" name="name" id="nameBasic" class="form-control" value="{{ $role->name
                 }}" required>
                <div class="invalid-tooltip">Please choose a unique and valid role name.</div>
                </div>
            </div>
            <div class="row g-2">
                <div class="col mb-0">
                <label for="emailBasic" class="form-label">Display Name</label>
                <input type="text" name="display_name" id="emailBasic" class="form-control" value="{{ $role->display_name
                }}"  required>
                <div class="invalid-tooltip">Please choose a unique and valid display name.</div>
                </div>
                <div class="col mb-0">
                <label for="dobBasic" class="form-label">Description</label>
                <input type="text" name="description" id="dobBasic" class="form-control" value="{{ $role->description
                }}"  required>
                <div class="invalid-tooltip">Please choose a description for this role.</div>
                </div>
            </div>

            @php  $previous_permission = "";  @endphp

            <div class="">
                <input
                    type="checkbox"
                    id="selectAll"
                    class="form-check-input"
                />
                <label class="checkboxSuccess1" for="selectAll" id="replace">Select All</label>
            </div>
            <div class="form--inline">
                @foreach ($permissions as $permission)
               
                    @if($previous_permission != $permission->description)
                        <div class="col mb-0" style="margin-top:10px;">
                            <input
                                type="checkbox"
                                class="form-check-input {{ lcfirst($permission->description) }}"
                                value="{{$permission->id}}"

                                onClick="selectPermission('{{ lcfirst($permission->description) }}')"
                            /> <!-- Ekhaney ja korar krte hbe -->

                            <label for="emailBasic" class="form-label">{{ ucfirst($permission->description) }}</label>
                        </div>
                    @endif
                        <div class="form-check form-switch mb-2 form-inline">
                            <input
                                class="form-check-input"
                                id="{{ lcfirst($permission->description) }}"
                                type="checkbox"
                                id="{{$permission->id}}"
                                name="permissions[]"
                                value="{{$permission->id}}"
                                @php if(isset($role_permission[$permission->id]) && $role_permission[$permission->id]) { @endphp checked @php }
                                @endphp
                            >
                            <label class="form-check-label" for="{{$permission->id}}">{{$permission->display_name}}</label>
                        </div>

                        @php
                            $previous_permission = $permission->description;
                            $check = isset( $permissions[$loop->index +1]->description) ? $permissions[$loop->index +1]->description : "-";
                        @endphp
                        @if($previous_permission != $check || $check == '-')@endif
                    @endforeach
                </div>
                <div class="fw-bold py-1 mt-3">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
               </div>
            </div>

            </form>
        </div>
    </div>
    </div>
</div>


@endsection

@push('script')
{{-- <x-utility.data-table-js/> --}}
<script>


</script>
@endpush

resources/views/backend/settings/role/index.blade.php
@extends('layouts.backend_master')
@section('title', 'Role')
@push('css')
<x-utility.datatable-css/>
@endpush
@section('master_content')
<div class="card">
    <div class="card-header ">
        <div class="d-flex justify-content-between">
        <h4 class="card-title">Manage Role</h4>
        <a href="{{ route('admin.role.create') }}" class="btn btn-success btn-sm"><i class="fa fa-plus"></i> Add New Role</a>
        </div>

    </div>
    <div class="card-body">
        <table class="table table-bordered" id="RoleTable">
            <thead>
                <tr>
                    <th>SL</th>
                    <th>Name</th>
                    <th>Display Name</th>
                    <th>Description Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($roles as $role)
                    <tr>
                        <td>{{ $loop->index + 1 }}</td>
                        <td>{{ $role->name }}</td>
                        <td>{{ $role->display_name }}</td>
                        <td>{{ $role->description }}</td>
                        <td>
                            <a href="{{ route('admin.role.edit',$role->id) }}" class="btn btn-sm btn-info"><i class="fa fa-edit"></i></a>
                           <form action="{{ route('admin.role.delete', $role->id) }}" class="d-inline" method="POST">
                            @csrf
                            @method('DELETE')
                            <button onclick=" return confirm('Are you Sure Delete This Data?')" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                           </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>


@endsection

@push('script')
<x-utility.datatable-js/>
<script>
   $('#RoleTable').DataTable();

</script>
@endpush